repos:
  - repo: local
    hooks:

      - id: block-main-branch
        name: prevent commits to main
        entry: bash -c 'branch=$(git rev-parse --abbrev-ref HEAD); if [ "$branch" = "main" ]; then echo "❌ Commit to main branch is not allowed."; exit 1; fi'
        language: system
        pass_filenames: false

      - id: prisma
        name: prisma checks
        entry: bash -c "cd backend && npx prisma format && npx prisma validate && npx prisma generate"
        language: system
        pass_filenames: false

      - id: eslint
        name: eslint --fix
        entry: bash -c "cd backend && npx eslint --fix ."
        language: system
        pass_filenames: false

      - id: prettier
        name: prettier --write
        entry: bash -c "cd backend && npx prettier --write ."
        language: system
        pass_filenames: false

      - id: typecheck
        name: tsc --noEmit
        entry: bash -c "cd backend && npx tsc --noEmit"
        language: system
        pass_filenames: false
