#!/bin/sh
# Faz git push + gh pr create usando a mensagem do último commit
# Uso: ./create-pr.sh [ISSUE_ID] [LINK_TYPE]
# Exemplos:
#   ./create-pr.sh 29 fixes
#   ./create-pr.sh 42 related

set -e

ISSUE="$1"
LINK_TYPE="${2:-fixes}" # padrão = fixes
MSG=$(git log -1 --pretty=%B | head -n 1)
BRANCH=$(git rev-parse --abbrev-ref HEAD)

git push -u origin "$BRANCH"

if [ -n "$ISSUE" ]; then
  BODY="$MSG\n\n${LINK_TYPE^} #$ISSUE"
else
  BODY="$MSG"
fi

gh pr create \
  --base main \
  --head "$BRANCH" \
  --title "$MSG" \
  --body "$BODY"

